### ISSUE TITLE
Hide activitiy for individual files (or anything)

### ISSUE THREAD

**Issue by Gomez** [owncloud/activity#114]
I have a file that gets updated all the time and spams my activity list. Would be cool to hide actions like this.

**Comment by nickvergessen** [comment]
Implementing the ignore/hide feature is not really hard. The question is, what's the best way to add "ignored files/items".
Doing that via the activity itself sounds like the best idea to me, but only works in some cases due to the grouping we perform.

I think a dropdown with the following options could be used:
```
* Ignore all activities for this file
* Ignore all activities of this type
* Ignore all activities of this type for this file
```
For a grouped activity the dropdown needs to be a bit different thou

**Comment by karlitschek** [comment]
I actually would do it the other way around. Add an option to show only the changes in the favorites

**Comment by rakekniven** [comment]
Please think of adding "Disable activity notifications" for folders as well.
e.g. I store my notepad++ settings in my ownCloud and that causes many, many activities a day.
