### ISSUE TITLE
Shouldn’t get notification emails about your own activity

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#152]
In the Activity notification settings, there are 4 things:
1. A new file or folder has been shared
2. A new file or folder has been created
3. A file or folder has been changed
4. A file or folder has been deleted

By default only 1 is sent via email notification and everything is in the stream.

Now for the stream it makes sense that when you tick 2,3,4 to show your own actions in there. But it doesn’t make sense at all to send you an email notification for your own changes.

When ticking the email option for 2,3,4 – you should only get email notifications when _someone else_ created/changed/deleted something.

@nickvergessen

**Comment by abrunstetter** [comment]
I can see a commit, referenced by nickvergessen, which adds another setting. I can't seem to find the setting, however in the github web UI. What am I missing?

**Comment by nickvergessen** [comment]
The setting is on the personal page below the notifications table

**Comment by abrunstetter** [comment]
I am still unable to find the setting. None of these settings control whether (or not) i receive notifications about my own changes.
Do I need to be an admin of my repo?

**Comment by nickvergessen** [comment]
Are you talking about owncloud or github?

In case of owncloud the setting is there:
![bildschirmfoto vom 2015-10-27 16 58 49](https://cloud.githubusercontent.com/assets/213943/10763939/3016512e-7ccc-11e5-94da-5ca346be9687.png)

But since you are speaking about github web ui, and repos I think you ended up at the wrong end of the internet.
