### ISSUE TITLE
Notification time is in UTC instead of my timezone

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/activity#175]
I got following mail today (at 16:56):

```
Hallo Morris,

Du erhälst diese E-Mail, da in der letzten Stunde
folgende Dinge auf / geschehen sind

* USER hat FILENAME mit Dir
geteilt - Heute 14:50:18
```

I don't know if it was shared at 15:50 or 14:50 but I guess 15:50 because the mail says "in the last hour". Therefore I guess it's a time conversion failure.

Is it possible to show the time in the timezone of the user (if it is somehow detectable - isn't it saved to the DB - cc @DeepDiver1975 )

**Comment by Bricecdb** [comment]
I know this thread is closed, but in case someone comes across it, this can help. My php.ini timezone was set correctly however the email notification timezone was UTC. To find if the server time was in the correct time zone, I created a php file, timezone.php and inserted the following code: 

<!doctype html>
<Html>
<body>
<?php
echo date_default_timezone_get();
?>
</body>
</html>

The above code will tell you what's your timezone. To get it to work copy the file under your Owncloud installation. Now navigate to your webpage for your cloud and at the end enter the file 
name which above was timezone.php. 
https://yourdomainname/owncloud/timezone.php

You will see if the php.ini is set correctly. Now if it is, the issue is not fixed yet, but at least you know your server timezone and the php.ini are correctly set. 

If the timezone changes it means the php.ini configuration is been overwritten somewhere else. Copy the file timezone.php in the activity folder which is under the folder call apps. 

Go to your cloud and go to the app activity. Now in the address bar, in the link after activity you need to put the following: activity/timezone.php
https://yourdomainname/owncloud/index.php/apps/activity/timezone.php

You will see the time zone changes to UTC. Now we know the activity app is overwriting the php.ini configuration for your time zone. 

The way to fix it, open the folder appinfo. Open the file app.php. At line #24, you will see the following: 
$l = OC_L10N::get('activity');
// add an navigation entry
OCP\App::addNavigationEntry(array(

Right above the line #24, insert the following: 
date_default_timezone_set('America/Los_Angeles');

Change the location of the timezone to yours. 

To make sure your timezone is set correctly, go to this link again: (make sure to change yourdomainname to yours)
https://yourdomainname/owncloud/index.php/apps/activity/timezone.php

And your timezone will be correct and the time on the email notification will be correct.
 
If you have done activity on your cloud right before doing this fix, your next email notification may not be correct. You can create new activities on your cloud and when you receive the email, check the time from the email with the actual activity app and look at the time stamp, it will match. Again the fix may not be working for the first email since some activity were recorded with the incorrect timezone. 

Hope this help! 

Cheers!

**Comment by nickvergessen** [comment]
The timezone is overwritten by owncloud itself:
https://github.com/owncloud/core/blob/master/lib/base.php#L529

There is also a lot of code relying on that value to be UTC.
Normally a login in the web UI should save your current timezone as a user setting (see table oc_preferences).
If that does not work, feel free to open an issue at https://github.com/owncloud/core/issues/new but do **not** modify any code directly

**Comment by Bricecdb** [comment]
@Nickvergessen

Correct at the login in the web UI does save my current time zone and yes the oc_preferences has my correct timezone. The activity app on the web browser does show the correct timestamp of the activity but not the email. The fix does correct the timestamp issue in the email. The activity_qm table keeps the time as Unix or Epoch format, which mean when I query the data, the database translate the time back to my timezone, why the activity app on the web browser works and my timestamps are correct. As for the email, the translation was missing. Everything works great!

**Comment by nickvergessen** [comment]
You could add `\OC::$server->getLogger()->error('user ' . $userName . ' has timezone ' . $timezone);`
at https://github.com/owncloud/activity/blob/master/lib/mailqueuehandler.php#L216 and then check the logs when the next email is being sent.

Second debugging step add before https://github.com/owncloud/activity/blob/master/lib/backgroundjob/emailnotification.php#L133:
```php
if (!empty($userTimezones[$user])) {
\OC::$server->getLogger()->error('user ' . $user . ' has custom timezone ' . $userTimezones[$user]);
} else {
\OC::$server->getLogger()->error('user ' . $user . ' has no custom timezone');
}
```

**Comment by Bricecdb** [comment]
Thanks will give that a try!

**Comment by Aka4Code** [comment]
@nickvergessen Why this issue is closed? This is still actual bug.
I am using Owncloud 9.1.1 and time in email notifications is wrong, and to fix this I have added `date_default_timezone_set('Europe/Warsaw');` inside `/apps/activity/appinfo/app.php`.

And yes, I have checked php.ini date.timezone option and it's correct ('Europe/Warsaw').

**Comment by flacco** [comment]
Hi,
this bug is unfixed in 9.1.7?

I've one question around this problem. Where gets 
"$userTimezones = $this->config->getUserValueForUsers('core', 'timezone', $affectedUsers);" in EmailNotification.php it's values from. $userTimezones seems always empty, so it will be filled with the DefaultTimezone. 

Where can I set the "timezone" value for users? We use an ActiveDirectory as our User-Backend.

Stefan

**Comment by flacco** [comment]
Hi,
another  question to this topic. Why is the default timzone hard-coded to UTC instead of an configurable value or taking it from php.ini?

Stefan
