### ISSUE TITLE
Question regarding the activity widget functionality

### ISSUE THREAD

**Issue by matthiasfromm** [owncloud/activity#214]
Hi all!

I am unsure about the functionality of the activity widget in a user's dashboard. On the website is says:
> See what is going on in your ownCloud. See who shared a file with you or when you created, changed or deleted files. Access the feed via RSS, an API for Desktop or Mobile clients or receive email notifications.

However that leaves me with an open question who can actually see what activities in my constellation of ownCloud. Here's an example with an admin, 1 super user and 3 other users:

* Admin installs and hosts the ownCloud
* User A creates a "main folder 1" with 2 subfolders ("subfolder a" and "subfolder b")
* User A shares the "main folder 1" with User B, the "subfolder a" with User C and the "subfolder b" with User D
* User B shares his own folder "User B files" with all other users
* User B enables the Activity Widget in his dashboard

My question is now, which activities will be listed in the Activity Widget of User B? Will only the activity in his own folder ("User B files") that he shared with other users be listed? Or will also be the activities listed that happen in "main folder 1" and its subfolder a and b?

I am indeed a bit puzzled and would be grateful for any advice, clarification or shared experience!

Just as an additional information: we are using LDAP (I don't if that is of any relevance).

Thanks & cheers,
Matthias

**Comment by nickvergessen** [comment]
Users see actions (delete, add, modify) that happen to files they have access to.
Sharing actions are only visible the the sharer and sharee.

In your case UserB sees:
* User A shares the "main folder 1" with User B
* User B shares his own folder "User B files" with all other users

However if C does something to "subfolder a", B will get an activity, since it affects his file syncing:
"User C deleted 'subfolder a/file.txt'"

**Comment by matthiasfromm** [comment]
Thanks Joas for such a quick response! That clarifies it, appreciate it!
