### ISSUE TITLE
Notifications of deleted files have wrong link target

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#262]
The notifications for file deletions, like
> You deleted **Document.pdf**

link the file wrongly. They point to the files app, with a scrollto to the document’s original position. Instead, it should point to the deleted files section.

@nickvergessen

**Comment by nickvergessen** [comment]
The problem with this is, that the files app triggers the notification, and not the files trashbin. Since we want to avoid inner app dependencies, the files app can not simply link to the trashbin. Also the file might not even be in the trashbin.

I agree that it is bad UX atm. Maybe we should just not link anywhere at all for the delete event.

**Comment by jancborchardt** [comment]
Hm .. for a delete event, restoring a file is important though. Can't we find a way to correctly link it or make it more useful?
Like - when the deleted files app is installed, correctly link it. If not, don't have it linked.

cc @schiesbn

**Comment by nickvergessen** [comment]
We could try and ask the IExtensions whether they know the parameter type and then we rename the parameter type on the delete activities from "file" to "deletedfile".
Then the trashbin can register an IExtension and do the magic to link to the trashbin and if it is not enabled, we will just do the normal markup stuff (bold, without linking)
