### ISSUE TITLE
notification center

### ISSUE THREAD

**Issue by karlitschek** [owncloud/activity#348]
New activities should be visible immediately in the web-interface. We should add a ’new notification’ icon in the ownCloud header. This icon should have a neutral color if no new activities are there and a highlight color if something new has happened. On click of the icon a small popup or dropdown should appear that show the latest X activities. At the bottom of the dropdown is a ’show more’ button that leads directly to the activity app where a user can see more and older entries.

Optional feature: Only the ‘more important’ activities should be visible in the notification area. So a standard file change should not be there but an invitation to a share or a change of a favorite file should appear there.

Optional feature:
This new activities should also trigger local web notificationhttp://www.w3.org/TR/notifications/

What do you think @nickvergessen @jancborchardt @MTRichards

**Comment by jancborchardt** [comment]
This is very related to the »permanent notifications« issue at https://github.com/owncloud/core/issues/17351 for more general use.

Since it’s quick-access and a small window, I’d say the main use-case of this notification popover is to quickly see things other people did. You know your own things, and seeing those is less important. I wouldn’t say it’s an optional feature to only show more important activites here, but the whole point – otherwise we just duplicate the activity app because we can.

**Comment by MTRichards** [comment]
Is there a way to provide a notification capability that this just leverages? While not a huge priority, we need a general notification capability for ownCloud for this like system wide messages - for things like maintenance windows, for example - admins have been asking for a while. Is this perhaps related / coverable with the same solution?

**Comment by karlitschek** [comment]
@jancborchardt I agree with everything.
@MTRichards Yes. This could be used to do system wide messages. Very easy once we have that.

**Comment by nickvergessen** [comment]
yeah let me have some thoughts after my vacation

**Comment by nickvergessen** [comment]
https://github.com/owncloud/notifications
