### ISSUE TITLE
File and folder renames do not show up as activity

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#375]
This should be the case though, as:

> `Username` renamed **oldfilename.txt** to **newfilename.txt**

@nickvergessen

**Comment by nickvergessen** [comment]
Yeah moving is missing, it's actually not that simple. When moving over boards, it can be rename,  move, add and delete for different persons on the same action. But yeah definetly on the todo, now where we have ids

**Comment by alvar-freude** [comment]
At the moment owncloud logs sometimes renamed folders and files as deleted+created. It may be good to detect all rename actions correct, but it's better to log a rename too then do nothing (when deleted+created, it will be logged).

As mentioned in owncloud/core#24176: 

In SQL we have a wonderful thing called triggers. Such things like history tables (like oc_activity) can't be wrong, when filled by triggers (except the triggers have bugs). And when everything is done right, it can't be manipulated by a broken app or unprivileged user (e.g. no write access to the history and changes in main table are logged automatically).
oc_filecache seems to miss a column "last_change_by" to log also the changing user.

I've done this for debugging (I try to detect moved files/folders), the SQL is here:


```SQL
-- 
-- Debug OwnCloud renamed files etc.
-- for all changed rows, add a history message in hist.filecache
-- 
-- It may be possible to log only name changes
-- for simplicity the function logs everything  
--
-- There is no permission management at the moment 
-- (revoke from public, grant to the admin user)
--

BEGIN;

CREATE SCHEMA hist;
CREATE TYPE hist.hist_type AS ENUM ('UPDATE', 'DELETE', 'TRUNCATE');
CREATE table hist.filecache 
       (
       LIKE oc_filecache EXCLUDING INDEXES EXCLUDING CONSTRAINTS, 
       operator hist.hist_type,
       valid_to TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
       ) WITH (FILLFACTOR=100);

CREATE INDEX hist_filecache_fileid ON hist.filecache(fileid) WITH (FILLFACTOR=100);   

CREATE OR REPLACE FUNCTION hist.filecache_changed() RETURNS TRIGGER AS
   $code$
      BEGIN
         INSERT INTO filecache VALUES (OLD.*, TG_OP::hist_type);
         RETURN NEW;
      END;
   $code$ 
   LANGUAGE 'plpgsql'
   SECURITY DEFINER
   SET search_path = hist, pg_temp;


CREATE TRIGGER filecache_changed BEFORE UPDATE OR DELETE ON oc_filecache
         FOR EACH ROW EXECUTE PROCEDURE hist.filecache_changed();

COMMIT;

```

**Comment by PVince81** [comment]
We can't use DB triggers as we have to support SQLite, Mysql/MariaDB, PostgreSQL, Oracle...

I'd normally expect that "rename" hooks are triggered.
I think the problem with activities was not about detecting the rename but mostly about how to link the activity back to the original file without file ids. Now that activities also support storing the fileid, it is possible to keep that connection.

**Comment by PVince81** [comment]
From what I see activity rename is quite complicated compared to other operations.
The reason is that we need not one path but two paths: $oldPath and $newPath from the hooks.

Also, these paths must be absolute because renaming/moving can make the owner of the file change when a share recipient moves a file out of the share. This will need special handling with special messages like "recipient X moved file F out of folder Y" for the other recipients, but for the person who moved it out a simple "you moved file F from path X to Y".

The tricky part from what I see is that the owner information needs to be gathered in the preRename hook. The target recipients needs to be precomputed there (while in other hooks the computation happens much later) for the old path, then in the postRename hook the recipients need to be computed again for the new path, separately.

So there will be two lists of recipients:
- activity recipients who will see the file moved away from the source
- activity recipients who will see the file moved into the target

And the list needs to be consolidated in case the source and target are the same parent, to avoid receiving two activities.

**Comment by PVince81** [comment]
WIP PR here https://github.com/owncloud/activity/pull/558
