### ISSUE TITLE
After upgrade from OC8.1 to 8.2 sidebar does not show pre update activities

### ISSUE THREAD

**Issue by butonic** [owncloud/activity#465]
The global app view does list activities for pre update files but selecting the detail view for them only produces an empty activity list.

Waiting for logs, but maybe this is already enough info.

**Comment by nickvergessen** [comment]
Yeah that's simply not possible.
The problem is previous we didn't store the object details for activities. So on DB level we didn't know:
1. Is this activity about a file
2. Which file is it about

Doing it in an update step is also not possible, because when you renamed folders etc we can not find the object either, or even find a wrong object, so the result is pre-update activities can not be bound to files.
New activities are bound to objects and therefor appear.

No unbound file activities should be created anymore, since I fixed all triggers. But the old entries in the db are :skull:
