### ISSUE TITLE
Show when a file was opened (option)

### ISSUE THREAD

**Issue by tombou** [owncloud/activity#524]
There is a way to log when someone access files and folders from the web platform directly in the activity stream? It can be an option actually that is disable by default because it may generate a lot of data.

**Comment by nickvergessen** [comment]
The problem is, that the system also opens a files, e.g. when creating thumbnails, versions, etc.
So that will really generate a lot of data and the worst thing about it: will make all those operations slow.
Since we need to get the list of people that have access to the file, what their path is, etc.

So I don't think that this is something we should do.
